using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using FrogAcross.Editor.Solver;
using FrogAcross.Levels;
using FrogAcross.Pieces;
using UnityEditor;
using UnityEngine;

namespace FrogAcross.Editor.Generator
{
    [Serializable]
    public sealed class SolvabilityEntry
    {
        public string id;
        public string fileHash; // SHA256 of the level file bytes
        public long minTicks;   // diagonal-free solver floor
        public bool solved;
    }

    [Serializable]
    public sealed class SolvabilityFixture
    {
        public string generated; // informational, set by the regenerate command
        public List<SolvabilityEntry> entries = new();
    }

    /// <summary>
    /// #62: the shipped set is locked behind solver proof. The fixture is a
    /// claim about specific bytes — CI verifies hashes cheaply; editing any
    /// level without re-running RegenerateFixture fails the suite.
    /// </summary>
    public static class ContentLock
    {
        public const string FixturePath = "Assets/Tests/EditMode/Content/levels-solvability.json";
        public const string LevelsFolder = "Assets/Resources/Levels";
        public const string ShippedPrefix = "level-";

        public static string[] ShippedLevelFiles() =>
            Directory.GetFiles(LevelsFolder, ShippedPrefix + "*.json").OrderBy(f => f).ToArray();

        public static string HashFile(string path)
        {
            using var sha = SHA256.Create();
            return BitConverter.ToString(sha.ComputeHash(File.ReadAllBytes(path))).Replace("-", "");
        }

        public static SolvabilityFixture LoadFixture() =>
            JsonUtility.FromJson<SolvabilityFixture>(File.ReadAllText(FixturePath));

        /// <summary>
        /// Re-hash the shipped files without re-solving. Valid ONLY after a
        /// change that cannot affect the sim — medal calibration (#63) is the
        /// one such step; sim-visible edits go through RegenerateFixture.
        /// </summary>
        public static void RefreshHashes()
        {
            var fixture = LoadFixture();
            foreach (var file in ShippedLevelFiles())
            {
                string id = Path.GetFileNameWithoutExtension(file);
                var entry = fixture.entries.FirstOrDefault(e => e.id == id)
                    ?? throw new InvalidOperationException($"{id}: not in fixture — run RegenerateFixture");
                entry.fileHash = HashFile(file);
            }
            File.WriteAllText(FixturePath, JsonUtility.ToJson(fixture, true));
            AssetDatabase.Refresh();
        }

        [MenuItem("FrogAcross/Levels/Regenerate solvability fixture")]
        public static void RegenerateFixture()
        {
            var registry = PieceRegistry.Load();
            var fixture = new SolvabilityFixture { generated = "regenerated by ContentLock.RegenerateFixture" };
            var sw = System.Diagnostics.Stopwatch.StartNew();
            foreach (var file in ShippedLevelFiles())
            {
                var level = LevelLoader.Parse(File.ReadAllText(file), registry);
                var solve = LevelSolver.Solve(level, allowDiagonals: false, 250_000, 10_800);
                if (!solve.Solved)
                    throw new InvalidOperationException(
                        $"{Path.GetFileName(file)} is not solvable ({solve.FailReason}) — a broken level must not be locked");
                fixture.entries.Add(new SolvabilityEntry
                {
                    id = Path.GetFileNameWithoutExtension(file),
                    fileHash = HashFile(file),
                    minTicks = solve.MinTicks,
                    solved = true,
                });
            }
            sw.Stop();
            Directory.CreateDirectory(Path.GetDirectoryName(FixturePath)!);
            File.WriteAllText(FixturePath, JsonUtility.ToJson(fixture, true));
            AssetDatabase.Refresh();
            Debug.Log($"[ContentLock] locked {fixture.entries.Count} levels in {sw.Elapsed.TotalSeconds:0.0}s → {FixturePath}");
        }
    }
}
